services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SpringApi
      MYSQL_USER: davi
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"